version: 0.0
os: linux
files:
  - source: src/
    destination: /home/ec2-user/app/release/src
  - source: scripts/
    destination: /home/ec2-user/app/release/scripts
  - source: package.json
    destination: /home/ec2-user/app/release
  - source: package-lock.json
    destination: /home/ec2-user/app/release
permissions:
  # change permissions from root to ec2-user
  - object: /home/ec2-user/app/release
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: stop-service.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start-service.sh
      timeout: 300
      runas: ec2-user