version: 0.0
os: linux
files:
  - source: src/
    destination: /home/ec2-user/app/src
  - source: scripts/
    destination: /home/ec2-user/app/scripts
  - source: package.json
    destination: /home/ec2-user/app
  - source: package-lock.json
    destination: /home/ec2-user/app
permissions:
  # change permissions from root to ec2-user
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-service.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-service.sh
      timeout: 300
      runas: ec2-user