version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
artifacts:
  files:
    - scripts/start-service.sh
    - scripts/install-dependencies.sh
    - scripts/stop-service.sh
    - src/server.js
    - package.json
    - package-lock.json
    - appspec.yml