version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm cache clean --force  # Optional: Clear npm cache
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - package-lock.json
    - appspec.yml
    - 'node_modules/**/*'