version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
artifacts:
  files:
    - start-service.sh
    - install-dependencies.sh
    - stop-service.sh
    - server.js
    - package.json
    - package-lock.json
    - appspec.yml